version: "3.5"

services:
    dfile:
        depends_on:
            - redis
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - SECRET_KEY_BASE=${DFILE_SECRET_KEY_BASE}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - API_KEY=${DFILE_API_KEY}
            - DFILE_PROCESSING_PATH=${DFILE_PROCESSING_PATH}
            - DFILE_TEST_PROCESSING_PATH=${DFILE_TEST_PROCESSING_PATH}
            - DFILE_STORE_PATH=${DFILE_STORE_PATH}
            - DFILE_PACKAGING_PATH=${DFILE_PACKAGING_PATH}
            - DFILE_TRASH_PATH=${DFILE_TRASH_PATH}
            - DFILE_CONFIGURATION_PATH=${DFILE_CONFIGURATION_PATH}
        networks:
            - default
    redis:
        image: redis:6.0.10
        volumes:
            - redis:/data
        command: redis-server
        networks:
            - default

volumes:
    redis:
networks:
    default:
        name: d-suit-net