version: "3.5"

services:
    dfile:
        depends_on:
            - redis
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - SECRET_KEY_BASE=${DFILE_SECRET_KEY_BASE}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - API_KEY=${DFILE_API_KEY}
    redis:
        image: redis:6.0.10
        volumes:
            - redis:/data
        command: redis-server

volumes:
    redis:
networks:
    default:
        name: d-suit-net